---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zcash-tnb-bundle
data:
  ARCHIVE_NAME: zcash-tnb-bundle-ab2b7c0-999170.tgz
  ARCHIVE_HTTP_SRC: https://gateway.pinata.cloud/ipfs/QmdmR3ShZnsWviFCLzWbmRwWoyuBrtRYzSpQfXNVEJ3RaD
  SNAPSHOT_NAME: zcash-testnet-miner-snap.tgz
  SNAPSHOT_HTTP_SRC:  https://gateway.pinata.cloud/ipfs/QmaZAmRfF8v9PhTJi8Ae8Kc6K41itbXZRt4UsHGnk7eKgZ
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zcashd-testnet-miner-config
data:
  ZCASHD_RPCPORT: "38232"
  zcash.conf: |
    listen=1
    testnet=1
    showmetrics=0
    logips=1
    dns=0
    gen=1
    experimentalfeatures=1
    txindex=1
    insightexplorer=0
    printtoconsole=1
    equihashsolver=tromp
    genproclimit=1
    rpcuser=zcashrpc
    rpcport=38232
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zcash-tnb-base
data:
  ZCASHD_NETWORK: "testnet"
  ZCASHD_RPCUSER: "zcashrpc"
  ZCASHD_LOGIPS: "1"
  ZCASHD_EXPERIMENTALFEATURES: "1"
  ZCASHD_TXINDEX: "1"
  ZCASHD_INSIGHTEXPLORER: "1"
  ZCASHD_ZMQPORT: "9904"
  ZCASHD_RPCBIND: "0.0.0.0"
  ZCASHD_RPCPORT: "38383"
  ZCASHD_ALLOWIP: "0.0.0.0/0"
